### ISSUE TITLE
App for offline usage in Play Framework

### ISSUE THREAD

**Issue by ramakrishnarama** [rnorth/dynamic-applicationCache-manifest-in-Play-framework#1]

**Comment by rnorth** [comment]
Hi!
This repository is _really_ old and probably very out of date, but I hope it's interesting to you in some way. Did you intend to raise an issue against it, or shall we close?
Thanks
Rich

**Comment by ramakrishnarama** [comment]
Hi Richard!!
No issues you can close it.
Thanks
Ram
